apiVersion: apps/v1
kind: DaemonSet
metadata:
  annotations:
    deprecated.daemonset.template.generation: "7"
  generation: 7
  labels:
    app: forwarder
    app.kubernetes.io/component: forwarder
    app.kubernetes.io/instance: fluentd
    app.kubernetes.io/managed-by: Tiller
    app.kubernetes.io/name: fluentd
    helm.sh/chart: fluentd-2.0.1
  name: fluentd
  namespace: default
spec:
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app.kubernetes.io/component: forwarder
      app.kubernetes.io/instance: fluentd
      app.kubernetes.io/name: fluentd
  template:
    metadata:
      labels:
        app: forwarder
        app.kubernetes.io/component: forwarder
        app.kubernetes.io/instance: fluentd
        app.kubernetes.io/managed-by: Tiller
        app.kubernetes.io/name: fluentd
        helm.sh/chart: fluentd-2.0.1
    spec:
      containers:
      - env:
        - name: FLUENTD_CONF
          value: fluentd.conf
        - name: FLUENTD_OPT
        - name: FLUENTD_DAEMON_USER
          value: root
        - name: FLUENTD_DAEMON_GROUP
          value: root
        - name: FLUENT_UID
          value: "0"
        image: docker.io/bitnami/fluentd:1.11.2-debian-10-r18
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 6
          httpGet:
            path: /fluentd.healthcheck?json=%7B%22ping%22%3A+%22pong%22%7D
            port: http
            scheme: HTTP
          initialDelaySeconds: 60
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 5
        name: fluentd
        ports:
        - containerPort: 9880
          name: http
          protocol: TCP
        readinessProbe:
          failureThreshold: 6
          httpGet:
            path: /fluentd.healthcheck?json=%7B%22ping%22%3A+%22pong%22%7D
            port: http
            scheme: HTTP
          initialDelaySeconds: 5
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 5
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /opt/bitnami/fluentd/conf
          name: fluentd-config
        - mountPath: /opt/bitnami/fluentd/logs/buffers
          name: buffer
        - mountPath: /var/log
          name: varlog
        - mountPath: /var/lib/docker/containers
          name: varlibdockercontainers
          readOnly: true
        - mountPath: /u01
          name: u01
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext:
        fsGroup: 0
        runAsUser: 0
      serviceAccount: fluentd-forwarder
      serviceAccountName: fluentd-forwarder
      terminationGracePeriodSeconds: 30
      volumes:
      - configMap:
          defaultMode: 420
          name: fluentd-forwarder-cm
        name: fluentd-config
      - emptyDir: {}
        name: buffer
      - hostPath:
          path: /var/log
          type: ""
        name: varlog
      - hostPath:
          path: /var/lib/docker/containers
          type: ""
        name: varlibdockercontainers
      - hostPath:
          path: /u01
          type: ""
        name: u01
  updateStrategy:
    rollingUpdate:
      maxUnavailable: 1
    type: RollingUpdate

